server:
  port: 8081
spring:
  application:
    name: "requests"
  webflux:
    base-path: "/"
  devtools:
    livereload:
      enabled: false
  profiles:
    active: "local"
  config:
    import: "optional:file:.env[.properties]"
  liquibase:
    enabled: true
    url: "jdbc:postgresql://${POSTGRES_HOST:${DB_HOST:localhost}}:${POSTGRES_PORT:${DB_PORT:5432}}/${POSTGRES_DB:${DB_NAME:authentication_db}}"
    user: "${POSTGRES_USER:${DB_USER:postgres}}"
    password: "${POSTGRES_PASSWORD:${DB_PASS:password}}"
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
logging:
  level:
    co.com.pragma: "DEBUG"
    org.springframework.web: "DEBUG"
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
routes:
  paths:
    global: "/api/v1"
adapters:
  r2dbc:
    host: "${POSTGRES_HOST:localhost}"
    port: "${POSTGRES_PORT:5432}"
    database: "${POSTGRES_DB:authentication_db}"
    schema: "public"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:root}"
  sqs:
    queues:
      emailQueue:
        region: "us-east-1"
        queueUrl: "${SQS_SENDER_EMAIL_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/225685253174/sqs_email_sender_to_ses}"
      reportQueue:
        region: "us-east-1"
        queueUrl: "${SQS_SENDER_QUEUE_REPORT_URL:https://sqs.us-east-1.amazonaws.com/225685253174/sqs_update_report}"
ms-authentication:
  base-url: "${AUTHENTICATION_BASE_URL:http://localhost:8080}"
  jwt-secret-key: "${APP_SECRET_KEY:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}"
  jwt-expiration: "${APP_EXP_TIME:3600000}"
entrypoint:
  lambda:
    base-url: "${LAMBDA_DEBT_CAPACITY_BASE_URL:https://tdiveru7v8.execute-api.us-east-1.amazonaws.com}"
  sqs:
    region: "us-east-1"
    # endpoint: "${SQS_LISTENER_QUEUE_ENDPOINT:http://localhost:4566}"
    queueUrl: "${SQS_LISTENER_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/225685253174/sqs_debt_capacity}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
